import {spawn} from 'node:child_process';
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';
import { Identity } from '../src/identity.js';
const root=path.resolve(import.meta.dirname,'..'),base=fs.mkdtempSync(path.join(os.tmpdir(),'neural-mesh-v09-explorer-')),pass='explorer-test-pass',procs=[];
const dirs={a:path.join(base,'a'),b:path.join(base,'b'),c:path.join(base,'c')};for(const d of Object.values(dirs))fs.mkdirSync(d,{recursive:true});
const ids={};for(const [k,d] of Object.entries(dirs))ids[k]=new Identity(d,{password:pass});const validators=Object.values(ids).map(x=>x.nodeId).join(',');
function start(name,port,extra={}){const env={...process.env,PORT:String(port),HOST:'127.0.0.1',PUBLIC_URL:`http://127.0.0.1:${port}`,DATA_DIR:dirs[name],MOCK_LLM:'true',LLM_MODEL:'mock-neuron',MAINLINE_DHT_ENABLED:'false',WALLET_PASSWORD:pass,NODE_KEY_PASSWORD:pass,ALLOW_INSECURE_KEYSTORE:'false',ADMISSION_POW_BITS:'4',WORK_POW_BITS:'4',DHT_REFRESH_MS:'700',BOOTSTRAP_VALIDATOR_IDS:validators,BOOTSTRAP_VALIDATOR_UNTIL_HEIGHT:'1000',CAPABILITIES:'general,reasoning,critic,validator',...extra};const p=spawn(process.execPath,['src/index.js'],{cwd:root,env,stdio:['ignore','pipe','pipe']});let logs='';p.stdout.on('data',d=>logs+=d);p.stderr.on('data',d=>logs+=d);p._logs=()=>logs;procs.push(p);return p;}
const A='http://127.0.0.1:48931',B='http://127.0.0.1:48932';start('a',48931,{RELAY_ENABLED:'true'});start('b',48932,{BOOTSTRAP_PEERS:A});start('c',48933,{PRIVATE_NODE:'true',PUBLIC_URL:'',BOOTSTRAP_PEERS:A,RELAY_PEERS:A});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
try{await sleep(7000);await fetch(B+'/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:'explorer telemetry integration test'})});await sleep(800);const r=await fetch(B+'/api/explorer');const x=await r.json();if(!r.ok)throw new Error(JSON.stringify(x));if(x.summary?.liveNeurons<3)throw new Error(`expected 3 live neurons, got ${x.summary?.liveNeurons}`);if((x.nodes||[]).length<3)throw new Error(`expected 3 signed snapshots, got ${x.nodes?.length}`);const privateNode=x.nodes.find(n=>n.nodeId===ids.c.nodeId);if(!privateNode||privateNode.mode!=='relay')throw new Error('private relay node missing from explorer');if(!x.edges?.length)throw new Error('peer graph has no edges');if(x.summary.totalCpuCores<3)throw new Error('compute aggregation failed');console.log('EXPLORER V0.9 OK',{live:x.summary.liveNeurons,edges:x.edges.length,privateRelay:true,tasksPerMinute:x.summary.tasksPerMinute,models:x.summary.models});}
catch(e){console.error(e);for(const p of procs)console.error(p._logs());process.exitCode=1;}finally{for(const p of procs)p.kill('SIGTERM');await sleep(700);}
