import {spawn} from 'node:child_process';
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import crypto from 'node:crypto';
import { Identity, canonical } from '../src/identity.js';
import { Wallet, parseNRN } from '../src/wallet.js';
import { Store } from '../src/db.js';

const root=path.resolve(import.meta.dirname,'..');const base=fs.mkdtempSync(path.join(os.tmpdir(),'neural-mesh-v06-'));const procs=[];const pass='test-v06-password';const token='test-admin-token';
const dirs={a:path.join(base,'a'),b:path.join(base,'b'),c:path.join(base,'c')};for(const d of Object.values(dirs))fs.mkdirSync(d,{recursive:true});
const identities={};const wallets={};for(const [k,d] of Object.entries(dirs)){identities[k]=new Identity(d,{password:pass});wallets[k]=new Wallet(d,{password:pass});}
const validatorIds=Object.values(identities).map(x=>x.nodeId).join(',');
function start(name,port,extra={}){const data=dirs[name];const env={...process.env,PORT:String(port),HOST:'127.0.0.1',PUBLIC_URL:`http://127.0.0.1:${port}`,DATA_DIR:data,MOCK_LLM:'true',LLM_MODEL:'mock-neuron',DISCOVERY_ENABLED:'false',DHT_REFRESH_MS:'1000',MAX_REMOTE_WORKERS:'2',VALIDATOR_COUNT:'3',VALIDATOR_QUORUM:'2',BOOTSTRAP_VALIDATOR_IDS:validatorIds,BOOTSTRAP_VALIDATOR_UNTIL_HEIGHT:'1000',TX_FEE_NRN:'0.00000100',MIN_VALIDATOR_STAKE_NRN:'0.00001000',CAPABILITIES:'general,reasoning,critic,validator',WALLET_PASSWORD:pass,NODE_KEY_PASSWORD:pass,ALLOW_INSECURE_KEYSTORE:'false',SECURITY_MODE:'testnet',ADMISSION_POW_BITS:'6',WORK_POW_BITS:'6',MAINLINE_DHT_ENABLED:'false',API_TOKEN:token,ALLOW_UNAUTHENTICATED_LOCAL:'false',CHAT_WAIT_REWARDS:'true',CHAT_FAST_PATH:'false',...extra};const p=spawn(process.execPath,['src/index.js'],{cwd:root,env,stdio:['ignore','pipe','pipe']});let logs='';p.stdout.on('data',d=>logs+=d);p.stderr.on('data',d=>logs+=d);p._logs=()=>logs;procs.push(p);return p;}
const A='http://127.0.0.1:48821',B='http://127.0.0.1:48822',C='http://127.0.0.1:48823';
start('a',48821,{RELAY_ENABLED:'true'});start('b',48822,{BOOTSTRAP_PEERS:A});start('c',48823,{PRIVATE_NODE:'true',PUBLIC_URL:'',BOOTSTRAP_PEERS:A,RELAY_PEERS:A});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function get(url){const r=await fetch(url);if(!r.ok)throw new Error(`${url} ${r.status}`);return r.json();}
async function post(url,obj,auth=true){const headers={'content-type':'application/json'};if(auth)headers.authorization=`Bearer ${token}`;const r=await fetch(url,{method:'POST',headers,body:JSON.stringify(obj)});const x=await r.json();return {status:r.status,x};}
try{
  await sleep(7000);const before=await get(B+'/api/status');if(before.stats.peers<2)throw new Error(`DHT/relay discovery failed: ${before.stats.peers} peers`);if(!before.security.encryptedWallet||!before.security.encryptedIdentity)throw new Error('encrypted keystore not active');
  const chat=await post(B+'/api/chat',{message:'hello secure distributed brain v0.7'},false);const x=chat.x;if(chat.status!==200||!x.answer||x.route?.length<3)throw new Error(`distributed chat failed: ${JSON.stringify(x)}`);if(!x.reward?.block||x.reward.claims<1)throw new Error(`validator/finality mint failed: ${JSON.stringify(x.reward)}`);
  await sleep(1200);let [sa,sb,sc]=await Promise.all([get(A+'/api/status'),get(B+'/api/status'),get(C+'/api/status')]);if(sa.ledger.height<1||sb.ledger.height<1||sc.ledger.height<1)throw new Error('reward block propagation failed');if(sa.ledger.head!==sb.ledger.head||sb.ledger.head!==sc.ledger.head)throw new Error('ledger heads diverged after reward');if(!sa.ledger.finalized||!sb.ledger.finalized||!sc.ledger.finalized)throw new Error('block is not finalized');

  const unauth=await post(B+'/api/wallet/send',{to:sc.wallet.address,amount:'0.00000100'},false);if(unauth.status!==401)throw new Error(`remote admin protection failed: ${unauth.status}`);

  const bondAmount='0.00002000';for(const url of [A,B,C]){const r=await post(url+'/api/validator/bond',{amount:bondAmount});if(r.status!==200||r.x.error||!r.x.block)throw new Error(`validator bond failed: ${url} ${JSON.stringify(r.x)}`);await sleep(400);}
  await sleep(1200);[sa,sb,sc]=await Promise.all([get(A+'/api/status'),get(B+'/api/status'),get(C+'/api/status')]);if(!sa.validator.bond||!sb.validator.bond||!sc.validator.bond)throw new Error('validator bonds did not propagate');

  const bondBefore=BigInt(sb.validator.bond.atomic);const slashHeight=Number(sb.ledger.height)+1,slashPrev=sb.ledger.head;const common={networkId:sb.networkId,type:'block-vote',height:slashHeight,round:0,prevHash:slashPrev,approved:true,reason:'ok',validatorId:identities.b.nodeId,rewardAddress:wallets.b.address,createdAt:Date.now()};const vote1=identities.b.envelope({...common,blockHash:'a'.repeat(64)}),vote2=identities.b.envelope({...common,blockHash:'b'.repeat(64)});const evidenceStore=new Store(dirs.a);evidenceStore.recordValidatorVote(vote1);const evidence=evidenceStore.recordValidatorVote(vote2);if(!evidence)throw new Error('double-vote slash evidence was not created');evidenceStore.close();const slashTrigger=await post(A+'/api/wallet/send',{to:sc.wallet.address,amount:'0.00001000'});if(slashTrigger.status!==200||!slashTrigger.x.block)throw new Error(`slash-trigger block failed: ${JSON.stringify(slashTrigger.x)}`);await sleep(1000);[sa,sb,sc]=await Promise.all([get(A+'/api/status'),get(B+'/api/status'),get(C+'/api/status')]);if(BigInt(sb.validator.bond.atomic)>=bondBefore)throw new Error('validator stake was not slashed after equivocation');if(sa.stats.pendingSlashings!==0)throw new Error('slash evidence was not consumed');

  const bBefore=parseNRN(sb.wallet.balanceNRN),cBefore=parseNRN(sc.wallet.balanceNRN);const amount='0.00010000';const sent=await post(B+'/api/wallet/send',{to:sc.wallet.address,amount});if(sent.status!==200||sent.x.error||!sent.x.tx?.txId||!sent.x.block)throw new Error(`wallet send failed: ${JSON.stringify(sent.x)}`);
  await sleep(1200);[sa,sb,sc]=await Promise.all([get(A+'/api/status'),get(B+'/api/status'),get(C+'/api/status')]);if(sa.ledger.head!==sb.ledger.head||sb.ledger.head!==sc.ledger.head)throw new Error('ledger heads diverged after transfer');if(parseNRN(sc.wallet.balanceNRN)!==cBefore+parseNRN(amount))throw new Error(`recipient balance mismatch ${sc.wallet.balanceNRN}`);if(parseNRN(sb.wallet.balanceNRN)>=bBefore)throw new Error('sender balance did not decrease');

  const replayEnv=identities.b.envelope({networkId:sb.networkId,fromIndex:0,limit:1});const first=await fetch(A+'/p2p/ledger/blocks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(replayEnv)});const second=await fetch(A+'/p2p/ledger/blocks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(replayEnv)});if(first.status!==200||second.status!==401)throw new Error(`replay protection failed ${first.status}/${second.status}`);

  const led=await get(B+'/api/ledger');const genesis=led.blocks.find(b=>b.index===0);const real1=led.blocks.find(b=>b.index===1);const body={version:4,index:1,round:0,networkId:sb.networkId,prevHash:genesis.hash,createdAt:Date.now()+1,proposer:identities.b.nodeId,proposerPublicKey:identities.b.publicPem,proposerRewardAddress:wallets.b.address,committee:real1.committee,threshold:real1.threshold,receipts:[],transactions:[],slashings:[],mintedNRN:'0',mintedAtomic:'0'};const hash=crypto.createHash('sha256').update(canonical(body)).digest('hex');const conflict={...body,hash,proposerSignature:identities.b.sign({hash}),validatorVotes:[],finalized:false};const env=identities.b.envelope({networkId:sb.networkId,block:conflict});const fork=await fetch(A+'/p2p/ledger/commit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(env)});if(fork.status!==409)throw new Error(`finalized fork was not rejected: ${fork.status}`);

  const phrase=new Wallet(dirs.b,{password:pass}).mnemonic;const restoreDir=fs.mkdtempSync(path.join(os.tmpdir(),'nrn-v06-restore-'));const restored=Wallet.fromMnemonic(restoreDir,phrase,{password:'restore-password'});if(restored.address!==sb.wallet.address)throw new Error('encrypted recovery phrase restored different address');
  console.log('SMOKE V0.7 SECURITY OK',{peers:before.stats.peers,neurons:x.route.length,rewardBlock:x.reward.block.index,height:sb.ledger.height,bondedValidators:sb.validator.eligibleValidators.length,transferBlock:sent.x.block.index,txId:sent.x.tx.txId.slice(0,16),replayProtection:true,remoteAdminProtection:true,finalizedForkRejected:true,slashing:true,recovery:true,privateRelayNode:true});
}catch(e){console.error(e);for(const p of procs)console.error(p._logs());process.exitCode=1;}finally{for(const p of procs)p.kill('SIGTERM');await sleep(700);}
