import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { canonical, Identity } from './identity.js';
import { deterministicCommittee, quorumFor } from './security.js';
import { validatorSetRoot as calcValidatorSetRoot, checkpointBody, checkpointHash } from './bft-state-machine.js';

export function epochForHeight(height, epochBlocks){return Math.floor(Math.max(0,Number(height)-1)/Math.max(1,Number(epochBlocks)||1));}
export function epochStartHeight(height, epochBlocks){const e=epochForHeight(height,epochBlocks);return e*Math.max(1,Number(epochBlocks)||1)+1;}
export function deterministicLeader({height,round,prevHash,validators=[]}){
  const xs=[...validators].sort();if(!xs.length)return '';
  const h=crypto.createHash('sha256').update(`${height}:${round}:${prevHash}`).digest();
  const n=h.readUInt32BE(0)%xs.length;return xs[n];
}
export function stateRoot(state){
  const balances=[...state.balances.entries()].map(([address,atomic])=>[address,atomic.toString()]).sort((a,b)=>a[0].localeCompare(b[0]));
  const nonces=[...state.nonces.entries()].map(([address,nonce])=>[address,Number(nonce)]).sort((a,b)=>a[0].localeCompare(b[0]));
  const bonds=[...state.bonds.values()].map(x=>({nodeId:x.nodeId,address:x.address,publicKey:x.publicKey,rewardAddress:x.rewardAddress,atomic:BigInt(x.atomic||0).toString(),jailUntilHeight:Number(x.jailUntilHeight)||0,slashedAtomic:BigInt(x.slashedAtomic||0).toString()})).sort((a,b)=>a.nodeId.localeCompare(b.nodeId));
  const pending=(state.pendingUnbonds||[]).map(x=>({address:x.address,atomic:BigInt(x.atomic).toString(),releaseHeight:Number(x.releaseHeight),validatorNodeId:x.validatorNodeId||''})).sort((a,b)=>a.releaseHeight-b.releaseHeight||a.address.localeCompare(b.address));
  return crypto.createHash('sha256').update(canonical({balances,nonces,bonds,pendingUnbonds:pending})).digest('hex');
}
function serializeState(state){return {balances:[...state.balances.entries()].map(([a,v])=>[a,BigInt(v).toString()]).sort((a,b)=>a[0].localeCompare(b[0])),nonces:[...state.nonces.entries()].map(([a,n])=>[a,Number(n)]).sort((a,b)=>a[0].localeCompare(b[0])),bonds:[...state.bonds.values()].map(x=>({...x,atomic:BigInt(x.atomic||0).toString(),slashedAtomic:BigInt(x.slashedAtomic||0).toString()})).sort((a,b)=>a.nodeId.localeCompare(b.nodeId)),pendingUnbonds:(state.pendingUnbonds||[]).map(x=>({...x,atomic:BigInt(x.atomic).toString()})),txIds:[...state.txIds].sort()};}
function stateFromSerialized(s){return {balances:new Map((s.balances||[]).map(([a,v])=>[a,BigInt(v)])),nonces:new Map(s.nonces||[]),bonds:new Map((s.bonds||[]).map(x=>[x.nodeId,{...x,atomic:BigInt(x.atomic),slashedAtomic:BigInt(x.slashedAtomic||0)}])),pendingUnbonds:(s.pendingUnbonds||[]).map(x=>({...x,atomic:BigInt(x.atomic)})),txIds:new Set(s.txIds||[])};}

export class SnapshotManager{
  constructor({config,identity,store,ledger=null}){this.c=config;this.identity=identity;this.store=store;this.ledger=ledger;this.dir=path.join(config.dataDir,'snapshots');fs.mkdirSync(this.dir,{recursive:true});}
  maybeCreate(block){if(!this.c.snapshotIntervalBlocks||Number(block.index)%this.c.snapshotIntervalBlocks!==0)return null;return this.create(block.index);}
  create(height=Number(this.store.ledgerHead().index)){
    const block=this.store.blockAtIndex(height);if(!block)throw new Error('snapshot block not found');const state=this.store.chainState(height);const serialized=serializeState(state);const validatorSet=this.ledger?.validatorSetSnapshot?.(height)||[...(state.bonds||new Map()).values()].map(x=>({...x,atomic:BigInt(x.atomic).toString()}));const vRoot=calcValidatorSetRoot(validatorSet);const body=checkpointBody({networkId:this.c.networkId,height:Number(height),blockHash:block.hash,stateRoot:block.stateRoot||stateRoot(state),validatorSetRoot:vRoot,totalSupplyAtomic:this.store.totalSupplyAtomic().toString(),state:serialized});body.block=block;body.validatorSet=validatorSet;body.epoch=epochForHeight(height,this.c.validatorEpochBlocks);body.createdAt=Date.now();const hash=checkpointHash(body);const proof=this.identity.envelope({networkId:this.c.networkId,type:'checkpoint-proposal',checkpointHash:hash,height:Number(height),blockHash:block.hash,stateRoot:body.stateRoot,validatorSetRoot:vRoot});const bundle={body,hash,proof,certificate:{votes:[],threshold:0,committee:[]}};const file=path.join(this.dir,`snapshot-${height}-${block.hash.slice(0,12)}.json`);fs.writeFileSync(file,JSON.stringify(bundle,null,2),{mode:0o600});this.store.upsertCheckpoint?.({height,blockHash:block.hash,stateRoot:body.stateRoot,file,proof:bundle,createdAt:body.createdAt});return {...bundle,file};
  }
  committee(bundle){const ids=(bundle?.body?.validatorSet||[]).map(x=>x.nodeId);return deterministicCommittee(`checkpoint:${bundle.body.height}:${bundle.body.blockHash}`,ids,this.c.validatorCount).map(x=>x.nodeId);}
  threshold(bundle){const n=this.committee(bundle).length;return n?Math.max(quorumFor(n),Math.min(this.c.validatorQuorum,n)):Infinity;}
  vote(bundle){const committee=this.committee(bundle);if(!committee.includes(this.identity.nodeId))throw new Error('not checkpoint committee');const v=this.verifyBody(bundle);if(!v.ok)throw new Error(v.reason);return this.identity.envelope({networkId:this.c.networkId,type:'checkpoint-vote',checkpointHash:bundle.hash,height:bundle.body.height,blockHash:bundle.body.blockHash,stateRoot:bundle.body.stateRoot,validatorSetRoot:bundle.body.validatorSetRoot,approved:true,validatorId:this.identity.nodeId,createdAt:Date.now()});}
  verifyBody(bundle){try{if(!bundle?.body||bundle.body.networkId!==this.c.networkId||checkpointHash(bundle.body)!==bundle.hash)return {ok:false,reason:'bad checkpoint hash/network'};const st=stateFromSerialized(bundle.body.state);if(stateRoot(st)!==bundle.body.stateRoot)return {ok:false,reason:'checkpoint state root mismatch'};if(calcValidatorSetRoot(bundle.body.validatorSet||[])!==bundle.body.validatorSetRoot)return {ok:false,reason:'checkpoint validator root mismatch'};if(bundle.body.block?.hash!==bundle.body.blockHash||Number(bundle.body.block?.index)!==Number(bundle.body.height))return {ok:false,reason:'checkpoint block mismatch'};return {ok:true};}catch(e){return {ok:false,reason:e.message};}}
  certify(bundle,votes=[]){const committee=this.committee(bundle),threshold=this.threshold(bundle),valid=new Map();for(const v of votes){if(!Identity.verifyEnvelope(v,Infinity))continue;const p=v.payload||{};if(p.type!=='checkpoint-vote'||p.networkId!==this.c.networkId||p.checkpointHash!==bundle.hash||!p.approved||!committee.includes(v.nodeId)||v.nodeId!==p.validatorId)continue;valid.set(v.nodeId,v);}if(valid.size<threshold)throw new Error('checkpoint quorum not reached');const out={...bundle,certificate:{committee,threshold,votes:[...valid.values()]}};const file=path.join(this.dir,`checkpoint-${bundle.body.height}-${bundle.hash.slice(0,12)}.json`);fs.writeFileSync(file,JSON.stringify(out,null,2),{mode:0o600});this.store.upsertCheckpoint({height:bundle.body.height,blockHash:bundle.body.blockHash,stateRoot:bundle.body.stateRoot,file,proof:out,createdAt:Date.now()});return {...out,file};}
  verifyCertified(bundle){const b=this.verifyBody(bundle);if(!b.ok)return b;const committee=this.committee(bundle),threshold=this.threshold(bundle),cert=bundle.certificate||{},valid=new Set();for(const v of cert.votes||[]){if(!Identity.verifyEnvelope(v,Infinity))continue;const p=v.payload||{};if(p.type==='checkpoint-vote'&&p.networkId===this.c.networkId&&p.checkpointHash===bundle.hash&&p.approved&&committee.includes(v.nodeId)&&v.nodeId===p.validatorId)valid.add(v.nodeId);}if(valid.size<threshold)return {ok:false,reason:'checkpoint certificate quorum'};const trusted=this.c.trustedCheckpointValidatorRoot;if(this.c.securityMode==='mainnet'&&trusted&&trusted!==bundle.body.validatorSetRoot)return {ok:false,reason:'checkpoint validator root not trusted'};if(this.c.securityMode==='mainnet'&&!trusted)return {ok:false,reason:'mainnet fast-sync requires TRUSTED_CHECKPOINT_VALIDATOR_ROOT'};return {ok:true,votes:valid.size,threshold};}
  importCertified(bundle){const v=this.verifyCertified(bundle);if(!v.ok)throw new Error(v.reason);const existing=Number(this.store.ledgerHead().index);if(existing>0&&existing>=Number(bundle.body.height))throw new Error('checkpoint is not ahead of local state');this.store.setFastSyncState({height:bundle.body.height,blockHash:bundle.body.blockHash,stateRoot:bundle.body.stateRoot,validatorSetRoot:bundle.body.validatorSetRoot,totalSupplyAtomic:bundle.body.totalSupplyAtomic,state:bundle.body.state,certificate:bundle.certificate});if(!this.store.hasBlock(bundle.body.blockHash))this.store.addBlock(bundle.body.block);return {ok:true,height:bundle.body.height,blockHash:bundle.body.blockHash,stateRoot:bundle.body.stateRoot};}
  latest(){return this.store.latestCheckpoint?.()||null;}
}
