import crypto from 'node:crypto';
import { canonical, Identity } from './identity.js';
function sha(x){return crypto.createHash('sha256').update(typeof x==='string'?x:canonical(x)).digest('hex');}
export class EvolutionAnchorManager{
  constructor({config,identity,store,ledger,collective}){this.c=config;this.identity=identity;this.store=store;this.ledger=ledger;this.collective=collective;}
  proposal(tournamentId){const t=this.store.collectiveTournament(tournamentId);if(!t||t.status!=='finalized')throw new Error('tournament not locally finalized');const tally=this.collective.tally(tournamentId);const votes=this.store.collectiveVotes(tournamentId);const consensus=this.ledger.head();const body={version:1,networkId:this.c.networkId,type:'evolution-anchor',tournamentId,winnerId:t.winnerId,tallyHash:sha(tally),ballotsHash:sha(votes.map(v=>v.proof)),consensusHeight:Number(consensus.index),consensusHash:consensus.hash,createdAt:Date.now()};const anchorId=sha(body);const committee=this.ledger.committee(`evolution:${anchorId}:${consensus.hash}`,Number(consensus.index));const threshold=this.ledger.threshold(committee);return {...body,anchorId,committee,threshold};}
  validateProposal(p){try{if(!p||p.networkId!==this.c.networkId||p.type!=='evolution-anchor')throw new Error('bad anchor network/type');const t=this.store.collectiveTournament(p.tournamentId);if(!t)throw new Error('unknown tournament');const tally=this.collective.tally(p.tournamentId);if(tally.voters<this.c.collectiveEvolutionMinVoters||tally.winnerId!==p.winnerId)throw new Error('winner/quorum mismatch');if(sha(tally)!==p.tallyHash)throw new Error('tally mismatch');const votes=this.store.collectiveVotes(p.tournamentId);if(sha(votes.map(v=>v.proof))!==p.ballotsHash)throw new Error('ballots mismatch');const b=this.store.blockAtIndex(Number(p.consensusHeight));if(!b||b.hash!==p.consensusHash)throw new Error('consensus anchor mismatch');const expected=sha({...p,anchorId:undefined,committee:undefined,threshold:undefined}); // not used
      const body={version:1,networkId:p.networkId,type:p.type,tournamentId:p.tournamentId,winnerId:p.winnerId,tallyHash:p.tallyHash,ballotsHash:p.ballotsHash,consensusHeight:Number(p.consensusHeight),consensusHash:p.consensusHash,createdAt:Number(p.createdAt)};if(sha(body)!==p.anchorId)throw new Error('anchor id mismatch');const committee=this.ledger.committee(`evolution:${p.anchorId}:${p.consensusHash}`,Number(p.consensusHeight));if(canonical(committee)!==canonical(p.committee||[])||Number(p.threshold)!==this.ledger.threshold(committee))throw new Error('anchor committee mismatch');return {ok:true};}catch(e){return {ok:false,reason:e.message};}}
  vote(p){const v=this.validateProposal(p);let approved=v.ok,reason=v.ok?'ok':v.reason;if(!(p.committee||[]).includes(this.identity.nodeId)){approved=false;reason='validator not selected for evolution committee';}return this.identity.envelope({networkId:this.c.networkId,type:'evolution-anchor-vote',anchorId:p.anchorId,tournamentId:p.tournamentId,winnerId:p.winnerId,consensusHash:p.consensusHash,approved,reason,createdAt:Date.now()});}
  certificate(p,votes){const valid=new Map();for(const v of votes||[]){if(!Identity.verifyEnvelope(v,Infinity)||v.payload?.type!=='evolution-anchor-vote'||v.payload?.anchorId!==p.anchorId||!v.payload?.approved||!(p.committee||[]).includes(v.nodeId))continue;valid.set(v.nodeId,v);}if(valid.size<Number(p.threshold))throw new Error(`evolution anchor needs ${p.threshold} validator votes`);const cert={...p,votes:[...valid.values()],status:'certified',blockIndex:0};this.store.upsertEvolutionAnchor(cert);return cert;}
  verifyCertificate(cert){const v=this.validateProposal(cert);if(!v.ok)return v;const valid=new Set();for(const x of cert.votes||[])if(Identity.verifyEnvelope(x,Infinity)&&x.payload?.type==='evolution-anchor-vote'&&x.payload?.anchorId===cert.anchorId&&x.payload?.approved&&(cert.committee||[]).includes(x.nodeId))valid.add(x.nodeId);return valid.size>=Number(cert.threshold)?{ok:true}:{ok:false,reason:'evolution anchor quorum'};}
}
