import crypto from 'node:crypto';
import { Identity, canonical } from './identity.js';

function sha(x){return crypto.createHash('sha256').update(canonical(x)).digest('hex');}
function ver(v){return String(v||'0').split('.').map(x=>Number.parseInt(x,10)||0);}
export function cmpVersion(a,b){const A=ver(a),B=ver(b);for(let i=0;i<Math.max(A.length,B.length);i++){const d=(A[i]||0)-(B[i]||0);if(d)return d<0?-1:1;}return 0;}
export class Governance {
  constructor({config,identity,store,ledger}){this.c=config;this.identity=identity;this.store=store;this.ledger=ledger;}
  committee(height){return this.ledger.validatorSetSnapshot(Number(height)).map(x=>x.nodeId).sort();}
  threshold(height){const n=this.committee(height).length;return Math.max(1,Math.floor((2*n)/3)+1);}
  proposalBody({targetVersion,minCompatibleVersion='0.13.0',releaseHash,activationHeight,changes={}}){return {type:'protocol-upgrade',networkId:this.c.networkId,targetVersion:String(targetVersion),minCompatibleVersion:String(minCompatibleVersion),releaseHash:String(releaseHash).toLowerCase(),activationHeight:Number(activationHeight),changes,createdAt:Date.now()};}
  create(x){const body=this.proposalBody(x);if(!/^\d+\.\d+\.\d+$/.test(body.targetVersion))throw new Error('invalid target version');if(!/^[a-f0-9]{64}$/.test(body.releaseHash))throw new Error('release hash must be sha256 hex');if(body.activationHeight<=Number(this.ledger.head().index)+this.c.governanceMinActivationDelay)throw new Error('activation height too soon');const proposalId=sha(body);const proof=this.identity.envelope({...body,proposalId});const p={...body,proposalId,authorNodeId:this.identity.nodeId,proof,status:'open'};this.store.upsertGovernanceProposal(p);return p;}
  verifyProposal(p){return !!(p&&p.networkId===this.c.networkId&&p.proposalId===sha({type:p.type,networkId:p.networkId,targetVersion:p.targetVersion,minCompatibleVersion:p.minCompatibleVersion,releaseHash:p.releaseHash,activationHeight:Number(p.activationHeight),changes:p.changes||{},createdAt:Number(p.createdAt)})&&Identity.verifyEnvelope(p.proof,Infinity)&&p.proof.nodeId===p.authorNodeId&&p.proof.payload?.proposalId===p.proposalId);}
  importProposal(p){if(!this.verifyProposal(p))throw new Error('invalid governance proposal');this.store.upsertGovernanceProposal(p);return {ok:true,proposalId:p.proposalId};}
  vote(proposalId,approve=true){const p=this.store.governanceProposal(proposalId);if(!p||!this.verifyProposal(p))throw new Error('unknown governance proposal');const committee=this.committee(p.activationHeight);if(!committee.includes(this.identity.nodeId))throw new Error('not governance validator');const proof=this.identity.envelope({type:'governance-vote',networkId:this.c.networkId,proposalId,approve:!!approve,targetVersion:p.targetVersion,activationHeight:p.activationHeight,validatorId:this.identity.nodeId,createdAt:Date.now()});this.store.putGovernanceVote({proposalId,nodeId:this.identity.nodeId,approve:!!approve,proof});return proof;}
  importVote(proof){if(!Identity.verifyEnvelope(proof,Infinity))throw new Error('invalid governance vote');const x=proof.payload||{},p=this.store.governanceProposal(x.proposalId);if(!p||x.networkId!==this.c.networkId||x.type!=='governance-vote'||proof.nodeId!==x.validatorId)return {ok:false};const committee=this.committee(p.activationHeight);if(!committee.includes(proof.nodeId))return {ok:false};this.store.putGovernanceVote({proposalId:x.proposalId,nodeId:proof.nodeId,approve:!!x.approve,proof});this.maybeSchedule(x.proposalId);return {ok:true};}
  maybeSchedule(proposalId){const p=this.store.governanceProposal(proposalId);if(!p)return null;const committee=this.committee(p.activationHeight),threshold=this.threshold(p.activationHeight);const votes=this.store.governanceVotes(proposalId).filter(v=>Identity.verifyEnvelope(v,Infinity)&&v.payload?.approve&&committee.includes(v.nodeId));const uniq=[...new Map(votes.map(v=>[v.nodeId,v])).values()];if(uniq.length<threshold)return null;const certificate={proposal:p,committee,threshold,votes:uniq};const scheduled={...p,status:'scheduled',certificate};this.store.upsertGovernanceProposal(scheduled);this.store.putGovernanceActivation({...scheduled,certificate,activated:false});return scheduled;}
  activeForHeight(height=Number(this.ledger.head().index)+1){const xs=this.store.governanceActivations().filter(x=>x.activationHeight<=Number(height)&&!this.store.governanceCancellation(x.proposalId)).sort((a,b)=>a.activationHeight-b.activationHeight);return xs.length?xs.at(-1):null;}
  verifyActivationCertificate(cert){try{const p=cert?.proposal;if(!this.verifyProposal(p))return {ok:false,reason:'bad governance proposal'};const committee=this.committee(p.activationHeight),threshold=this.threshold(p.activationHeight);if(canonical(committee)!==canonical(cert.committee||[])||Number(cert.threshold)!==threshold)return {ok:false,reason:'bad governance committee'};const valid=new Map();for(const v of cert.votes||[]){if(!Identity.verifyEnvelope(v,Infinity))continue;const x=v.payload||{};if(x.type==='governance-vote'&&x.networkId===this.c.networkId&&x.proposalId===p.proposalId&&x.approve&&committee.includes(v.nodeId)&&v.nodeId===x.validatorId)valid.set(v.nodeId,v);}if(valid.size<threshold)return {ok:false,reason:'governance quorum'};return {ok:true,proposal:p};}catch(e){return {ok:false,reason:e.message};}}
  importActivationCertificate(cert){const v=this.verifyActivationCertificate(cert);if(!v.ok)throw new Error(v.reason);const p={...v.proposal,status:'scheduled',certificate:cert};this.store.upsertGovernanceProposal(p);this.store.putGovernanceActivation({...p,certificate:cert,activated:Number(this.ledger.head().index)>=Number(p.activationHeight)});return p;}
  rootEntries(height=Number(this.ledger.head().index)+1){return this.store.governanceActivations().filter(x=>x.activationHeight<=Number(height)&&!this.store.governanceCancellation(x.proposalId)).map(x=>({proposalId:x.proposalId,targetVersion:x.targetVersion,minCompatibleVersion:x.minCompatibleVersion,releaseHash:x.releaseHash,activationHeight:x.activationHeight})).sort((a,b)=>a.activationHeight-b.activationHeight||a.proposalId.localeCompare(b.proposalId));}
  root(height=Number(this.ledger.head().index)+1){return sha(this.rootEntries(height));}
  rootWithCertificate(cert,height){const v=this.verifyActivationCertificate(cert);if(!v.ok)return '';const p=v.proposal;const xs=this.rootEntries(height).filter(x=>x.proposalId!==p.proposalId);if(Number(p.activationHeight)<=Number(height))xs.push({proposalId:p.proposalId,targetVersion:p.targetVersion,minCompatibleVersion:p.minCompatibleVersion,releaseHash:p.releaseHash,activationHeight:Number(p.activationHeight)});xs.sort((a,b)=>a.activationHeight-b.activationHeight||a.proposalId.localeCompare(b.proposalId));return sha(xs);}
  requiredVersion(height=Number(this.ledger.head().index)+1){const xs=this.store.governanceActivations().filter(x=>x.activationHeight<=Number(height)&&!this.store.governanceCancellation(x.proposalId)).sort((a,b)=>a.activationHeight-b.activationHeight);return xs.length?xs.at(-1).targetVersion:this.c.baseProtocolVersion;}
  minCompatibleVersion(height=Number(this.ledger.head().index)+1){const xs=this.store.governanceActivations().filter(x=>x.activationHeight<=Number(height)&&!this.store.governanceCancellation(x.proposalId)).sort((a,b)=>a.activationHeight-b.activationHeight);return xs.length?xs.at(-1).minCompatibleVersion:this.c.baseMinCompatibleVersion;}
  localCompatible(height){return cmpVersion(this.c.protocolVersion,this.minCompatibleVersion(height))>=0;}
  cancelActivation(proposalId,certificate){const a=this.store.governanceActivations().find(x=>x.proposalId===proposalId);if(!a)throw new Error('unknown scheduled upgrade');if(Number(this.ledger.head().index)>=Number(a.activationHeight))throw new Error('cannot cancel activated upgrade');this.store.putGovernanceCancellation(proposalId,certificate);const p=this.store.governanceProposal(proposalId);if(p)this.store.upsertGovernanceProposal({...p,status:'cancelled',cancelCertificate:certificate});return {ok:true,proposalId};}
  status(){const h=Number(this.ledger.head().index)+1;return {protocolVersion:this.c.protocolVersion,requiredVersion:this.requiredVersion(h),minCompatibleVersion:this.minCompatibleVersion(h),compatible:this.localCompatible(h),governanceRoot:this.root(h),proposals:this.store.governanceProposals(),activations:this.store.governanceActivations(),cancellations:this.store.governanceCancellations()};}
}
