import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { Identity, canonical } from './identity.js';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const trainerPath=path.resolve(__dirname,'../trainer/trainer.py');
function sha256Buffer(b){return crypto.createHash('sha256').update(b).digest('hex');}
function sha256Json(x){return crypto.createHash('sha256').update(canonical(x)).digest('hex');}
function safeId(x){return String(x||'').replace(/[^a-zA-Z0-9_.-]/g,'_').slice(0,128);}
function run(cmd,args,{timeout=60000,env={}}={}){return new Promise((resolve,reject)=>{let out='',err='';const p=spawn(cmd,args,{env:{...process.env,...env},stdio:['ignore','pipe','pipe']});const t=setTimeout(()=>{p.kill('SIGKILL');reject(new Error(`process timeout: ${cmd}`));},timeout);p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('error',e=>{clearTimeout(t);reject(e)});p.on('close',code=>{clearTimeout(t);code===0?resolve({out,err}):reject(new Error(`${cmd} exited ${code}: ${(err||out).slice(-4000)}`));});});}

export class TrainingEngine {
  constructor({config,identity,store,llm,contentStore=null}){this.c=config;this.identity=identity;this.store=store;this.llm=llm;this.contentStore=contentStore;this.running=false;this.timer=null;this.lastRunAt=0;this._readyCache=null;this._readyCacheAt=0;fs.mkdirSync(this.c.trainingAdapterDir,{recursive:true});}
  enabled(){return !!this.c.trainingEnabled;}
  async readiness(){
    if(this._readyCache&&Date.now()-this._readyCacheAt<60000)return this._readyCache;
    if(!this.enabled())return {enabled:false,ready:false,mode:'disabled'};
    if(this.c.trainingMode==='mock'){this._readyCache={enabled:true,ready:true,mode:'mock'};this._readyCacheAt=Date.now();return this._readyCache;}
    try{const r=await run(this.c.trainingPython,[trainerPath,'--check'],{timeout:15000});const x=JSON.parse(r.out.trim().split(/\n/).at(-1));this._readyCache={enabled:true,ready:!!x.ready,mode:x.ready?'peft':'unavailable',details:x};}catch(e){this._readyCache={enabled:true,ready:false,mode:'unavailable',error:e.message};}this._readyCacheAt=Date.now();return this._readyCache;
  }
  dataset(){return this.store.knowledgeArtifacts(this.c.trainingMaxArtifacts).filter(a=>a.type==='distillation'&&a.quality>=this.c.trainingMinQuality&&a.payload?.question&&a.payload?.answer).slice(0,this.c.trainingMaxArtifacts);}
  async train({force=false,domain='general'}={}){
    if(this.running)throw new Error('training already running');if(!this.enabled())throw new Error('training disabled');
    const artifacts=this.dataset().filter(a=>domain==='general'||a.domain===domain);if(artifacts.length<this.c.trainingMinArtifacts&&!force)throw new Error(`need ${this.c.trainingMinArtifacts} training artifacts; have ${artifacts.length}`);
    const ready=await this.readiness();if(!ready.ready)throw new Error(`trainer unavailable${ready.error?`: ${ready.error}`:''}`);
    this.running=true;const createdAt=Date.now();const data=artifacts.map(a=>({instruction:a.payload.question,response:a.payload.answer,domain:a.domain,quality:a.quality,artifactId:a.artifactId}));const datasetHash=sha256Json(data);const runId=`train_${createdAt}_${this.identity.nodeId.slice(0,8)}`;const runDir=path.join(this.c.trainingAdapterDir,runId);fs.mkdirSync(runDir,{recursive:true});const datasetFile=path.join(runDir,'dataset.jsonl');fs.writeFileSync(datasetFile,data.map(x=>JSON.stringify(x)).join('\n')+'\n');
    this.store.upsertTrainingRun({runId,nodeId:this.identity.nodeId,baseModel:this.c.trainingBaseModel,mode:ready.mode,status:'running',datasetHash,artifactCount:data.length,createdAt});
    try{
      const args=[trainerPath,'train','--dataset',datasetFile,'--output',runDir,'--base-model',this.c.trainingBaseModel,'--epochs',String(this.c.trainingEpochs),'--batch-size',String(this.c.trainingBatchSize),'--learning-rate',String(this.c.trainingLearningRate),'--lora-rank',String(this.c.trainingLoraRank),'--lora-alpha',String(this.c.trainingLoraAlpha),'--mode',ready.mode];
      const r=await run(this.c.trainingPython,args,{timeout:this.c.trainingTimeoutMs});const result=JSON.parse(r.out.trim().split(/\n/).at(-1));const bundle=fs.readFileSync(result.bundle);if(bundle.length>this.c.trainingMaxAdapterBytes)throw new Error(`adapter bundle too large: ${bundle.length}`);
      const cas=this.contentStore?.putBuffer(bundle,{kind:'lora-adapter',source:this.identity.nodeId,meta:{baseModel:this.c.trainingBaseModel,domain,runId,datasetHash}});
      const bundleSha256=cas?.hash||sha256Buffer(bundle),bundlePath=cas?.localPath||result.bundle;
      const manifestCore={version:2,networkId:this.c.networkId,type:'lora-adapter',authorNodeId:this.identity.nodeId,baseModel:this.c.trainingBaseModel,ollamaBaseModel:this.c.trainingOllamaBaseModel,domain,runId,datasetHash,artifactCount:data.length,bundleSha256,contentHash:bundleSha256,bundleBytes:bundle.length,metrics:result.metrics||{},createdAt};const adapterId=sha256Json(manifestCore);const proof=this.identity.envelope({networkId:this.c.networkId,type:'adapter-manifest',adapterId,manifest:manifestCore});const manifest={...manifestCore,adapterId};const score=Number(result.metrics?.score??result.metrics?.eval_score??0.75);
      this.store.upsertModelAdapter({adapterId,authorNodeId:this.identity.nodeId,baseModel:manifest.baseModel,domain,manifest,proof,status:'candidate',benchmarkScore:score,localPath:bundlePath,createdAt});this.store.upsertTrainingRun({runId,nodeId:this.identity.nodeId,baseModel:this.c.trainingBaseModel,mode:ready.mode,status:'complete',datasetHash,artifactCount:data.length,adapterId,metrics:result.metrics||{},createdAt});this.lastRunAt=Date.now();return this.store.modelAdapter(adapterId);
    }catch(e){this.store.upsertTrainingRun({runId,nodeId:this.identity.nodeId,baseModel:this.c.trainingBaseModel,mode:ready.mode,status:'failed',datasetHash,artifactCount:data.length,error:e.message,createdAt});throw e;}finally{this.running=false;}
  }
  publicManifest(a){return a?{adapterId:a.adapterId,authorNodeId:a.authorNodeId,baseModel:a.baseModel,domain:a.domain,manifest:a.manifest,proof:a.proof,status:a.status,benchmarkScore:a.benchmarkScore,createdAt:a.createdAt}:null;}
  importManifest(a){if(!this.c.trainingImportAdapters)throw new Error('adapter import disabled');if(!a?.proof||!Identity.verifyEnvelope(a.proof,this.c.envelopeMaxSkewMs))throw new Error('invalid adapter signature');const p=a.proof.payload;if(p?.networkId!==this.c.networkId||p?.type!=='adapter-manifest'||p?.adapterId!==a.adapterId||a.proof.nodeId!==a.authorNodeId)throw new Error('adapter identity/network mismatch');if(sha256Json(p.manifest)!==a.adapterId)throw new Error('adapter manifest hash mismatch');if(Number(p.manifest.bundleBytes)>this.c.trainingMaxAdapterBytes)throw new Error('adapter too large');this.store.upsertModelAdapter({...a,manifest:p.manifest,status:'remote',localPath:''});if(this.contentStore&&p.manifest.contentHash)this.contentStore.noteProvider(p.manifest.contentHash,a.authorNodeId,0.8);return {accepted:true,adapterId:a.adapterId,contentHash:p.manifest.contentHash||p.manifest.bundleSha256};}
  bundle(adapterId){const a=this.store.modelAdapter(adapterId);if(!a||!a.localPath||!fs.existsSync(a.localPath))throw new Error('adapter bundle unavailable');const b=fs.readFileSync(a.localPath);if(b.length>this.c.trainingMaxAdapterBytes)throw new Error('adapter too large');return {adapterId,sha256:sha256Buffer(b),bytes:b.length,data:b.toString('base64')};}
  bundleInfo(adapterId,chunkBytes=256*1024){const a=this.store.modelAdapter(adapterId);if(!a||!a.localPath||!fs.existsSync(a.localPath))throw new Error('adapter bundle unavailable');const st=fs.statSync(a.localPath);if(st.size>this.c.trainingMaxAdapterBytes)throw new Error('adapter too large');return {adapterId,sha256:a.manifest.bundleSha256,bytes:st.size,chunkBytes,chunks:Math.ceil(st.size/chunkBytes)};}
  bundleChunk(adapterId,index,chunkBytes=256*1024){const info=this.bundleInfo(adapterId,chunkBytes),i=Number(index);if(!Number.isInteger(i)||i<0||i>=info.chunks)throw new Error('invalid adapter chunk');const a=this.store.modelAdapter(adapterId),fd=fs.openSync(a.localPath,'r');try{const start=i*chunkBytes,len=Math.min(chunkBytes,info.bytes-start),buf=Buffer.alloc(len);fs.readSync(fd,buf,0,len,start);return {adapterId,index:i,chunks:info.chunks,bytes:info.bytes,sha256:info.sha256,data:buf.toString('base64')};}finally{fs.closeSync(fd);}}
  importBundleBuffer(adapterId,b){const a=this.store.modelAdapter(adapterId);if(!a)throw new Error('unknown adapter manifest');if(!Buffer.isBuffer(b)||!b.length||b.length>this.c.trainingMaxAdapterBytes)throw new Error('bad adapter bundle size');if(sha256Buffer(b)!==a.manifest.bundleSha256)throw new Error('adapter bundle hash mismatch');const cas=this.contentStore?.importBuffer(a.manifest.contentHash||a.manifest.bundleSha256,b,{kind:'lora-adapter',source:a.authorNodeId,meta:{adapterId,baseModel:a.baseModel,domain:a.domain}});const f=cas?.localPath||path.join(this.c.trainingAdapterDir,`${safeId(adapterId)}.zip`);if(!cas)fs.writeFileSync(f,b,{mode:0o600});const score=this.benchmarkManifest(a);this.store.upsertModelAdapter({...a,status:score>=this.c.trainingBenchmarkMinScore?'verified':'rejected',benchmarkScore:score,localPath:f});if(this.contentStore)this.contentStore.noteProvider(a.manifest.contentHash||a.manifest.bundleSha256,this.identity.nodeId,1);return {accepted:score>=this.c.trainingBenchmarkMinScore,adapterId,score,contentHash:a.manifest.contentHash||a.manifest.bundleSha256};}
  importBundle(adapterId,packet){const a=this.store.modelAdapter(adapterId);if(!a)throw new Error('unknown adapter manifest');if(packet?.sha256&&packet.sha256!==a.manifest.bundleSha256)throw new Error('adapter bundle hash mismatch');return this.importBundleBuffer(adapterId,Buffer.from(packet?.data||'','base64'));}
  benchmarkManifest(a){const m=a.manifest||{};let score=0.5;score+=Math.min(.2,Number(m.metrics?.score||0)*.2);score+=m.artifactCount>=this.c.trainingMinArtifacts?.15:.05;score+=m.bundleBytes>100?.1:0;return Number(Math.min(.99,score).toFixed(4));}
  makeVote(adapterId){const a=this.store.modelAdapter(adapterId);if(!a)throw new Error('unknown adapter');const score=Math.max(a.benchmarkScore||0,this.benchmarkManifest(a));const roundId=`adapter_${Math.floor(Date.now()/this.c.federatedRoundMs)}`;const payload={networkId:this.c.networkId,type:'adapter-vote',roundId,nodeId:this.identity.nodeId,adapterId,score,createdAt:Date.now()};const proof=this.identity.envelope(payload);const v={...payload,proof};this.store.addAdapterVote(v);return v;}
  importVote(proof){if(!Identity.verifyEnvelope(proof,this.c.envelopeMaxSkewMs))throw new Error('invalid adapter vote');const p=proof.payload;if(p?.networkId!==this.c.networkId||p?.type!=='adapter-vote'||p.nodeId!==proof.nodeId||!this.store.modelAdapter(p.adapterId))throw new Error('invalid adapter vote payload');this.store.addAdapterVote({...p,proof});return {accepted:true};}
  consensus(adapterId,roundId=null){const rid=roundId||`adapter_${Math.floor(Date.now()/this.c.federatedRoundMs)}`;const vs=this.store.adapterVotes(rid,adapterId);if(vs.length<this.c.federatedMinParticipants)return {roundId:rid,adapterId,participants:vs.length,approved:false,score:0};const score=vs.reduce((s,v)=>s+v.score,0)/vs.length;const approved=score>=this.c.trainingBenchmarkMinScore;if(approved){const a=this.store.modelAdapter(adapterId);if(a)this.store.upsertModelAdapter({...a,status:'federated-approved',benchmarkScore:score});}return {roundId:rid,adapterId,participants:vs.length,approved,score:Number(score.toFixed(4))};}
  async activate(adapterId){const a=this.store.modelAdapter(adapterId);if(!a?.localPath)throw new Error('adapter not downloaded');if(!['verified','federated-approved','candidate'].includes(a.status))throw new Error(`adapter status ${a.status} not activatable`);const outDir=path.join(this.c.trainingAdapterDir,`unpacked-${safeId(adapterId)}`);fs.mkdirSync(outDir,{recursive:true});await run(this.c.trainingPython,[trainerPath,'unpack','--bundle',a.localPath,'--output',outDir],{timeout:30000});if(this.c.llmProvider!=='ollama')return {ok:true,adapterId,activated:false,reason:'runtime is not Ollama'};const modelName=`neural-${adapterId.slice(0,12)}`;const modelfile=path.join(outDir,'Modelfile');fs.writeFileSync(modelfile,`FROM ${a.manifest.ollamaBaseModel||this.c.trainingOllamaBaseModel}\nADAPTER ${outDir}\n`);try{await run('ollama',['create',modelName,'-f',modelfile],{timeout:10*60_000});const old=this.c.llmModel;this.c.llmModel=modelName;try{await this.llm.chat([{role:'user',content:'Reply only OK'}],{model:modelName});}catch(e){this.c.llmModel=old;throw e;}const updated={...a,status:'active',localPath:a.localPath};this.store.upsertModelAdapter(updated);return {ok:true,adapterId,activated:true,model:modelName};}catch(e){throw new Error(`Ollama adapter activation failed: ${e.message}`);}}
  async status(){return {enabled:this.enabled(),running:this.running,lastRunAt:this.lastRunAt,readiness:await this.readiness(),runs:this.store.trainingRuns(10),adapters:this.store.modelAdapters(20)};}
  start({onAdapter}={}){if(!this.c.trainingAuto||this.timer)return;this.timer=setInterval(async()=>{if(this.running||Date.now()-this.lastRunAt<this.c.trainingIntervalMs)return;try{const a=await this.train();if(a&&onAdapter)await onAdapter(a);}catch{}},Math.max(60000,Math.min(this.c.trainingIntervalMs,10*60_000)));this.timer.unref?.();}
  stop(){if(this.timer)clearInterval(this.timer);this.timer=null;}
}
